string[]                            target_objects   # object to look for
string                              target_location
---
bool                                success         # indicate successful run of triggered service
